import keyMirror from 'keymirror';

export default keyMirror({
  CHANGE_EVENT: null,

  LIST_USERS_REQUEST: null,
  LIST_USERS_SUCCESS: null,
  LIST_USERS_FAILURE: null,

  GET_USER_REQUEST: null,
  GET_USER_SUCCESS: null,
  GET_USER_FAILURE: null,

  LIST_GROUPS_REQUEST: null,
  LIST_GROUPS_SUCCESS: null,
  LIST_GROUPS_FAILURE: null,

  GET_GROUP_REQUEST: null,
  GET_GROUP_SUCCESS: null,
  GET_GROUP_FAILURE: null,

  LIST_NOTES_REQUEST: null,
  LIST_NOTES_SUCCESS: null,
  LIST_NOTES_FAILURE: null,

  GET_NOTE_REQUEST: null,
  GET_NOTE_SUCCESS: null,
  GET_NOTE_FAILURE: null,

  CREATE_NOTE_REQUEST: null,
  CREATE_NOTE_SUCCESS: null,
  CREATE_NOTE_FAILURE: null,

  UPDATE_NOTE_REQUEST: null,
  UPDATE_NOTE_SUCCESS: null,
  UPDATE_NOTE_FAILURE: null,

  DELETE_NOTE_REQUEST: null,
  DELETE_NOTE_SUCCESS: null,
  DELETE_NOTE_FAILURE: null
});
